const SERVER = 'https://rently-service-backend.herokuapp.com/api';


const DATAGRID_RESULTS_PER_PAGE = 20;
// TODO: compute client screen width
const DATAGRID_WIDTH = 1200;


const CLOUDINARY_URL = 'cloudinary://524458174797441:x2MQJicIN5bP7zZP2C_pAFBeLCM@rently-service'
const CLOUDINARY_CLOUD_NAME = 'rently-service'
const CLOUDINARY_API_KEY = '524458174797441'
const CLOUDINARY_SECRET = 'x2MQJicIN5bP7zZP2C_pAFBeLCM'

export {
    SERVER, DATAGRID_RESULTS_PER_PAGE, DATAGRID_WIDTH, CLOUDINARY_URL, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_SECRET
}